### ISSUE TITLE
Suggest add command to open man page in new tab

### ISSUE THREAD

**Issue by hiberabyss** [vim-utils/vim-man#27]
Sometimes the man page is long, it will be useful to open man page in new tab instead just a spilt window. Thanks.

**Comment by bruno-** [comment]
Yea, this would be useful, I'd accept a PR for this.

I wonder if it would be possible to make it work with vim's `:tab cmd` combo, see `:help :tab`.

**Comment by bruno-** [comment]
This was implemented in #30, thanks @hiberabyss
