### ISSUE TITLE
g:loaded_man clash in neovim

### ISSUE THREAD

**Issue by sakhnik** [vim-utils/vim-man#33]
After recent changes to vim-man, an error shows up when trying to look up a man page in neovim:
![vim-man-nvim](https://cloud.githubusercontent.com/assets/364912/11194856/358a1af0-8cb7-11e5-8122-daa359bca95f.png)
Though, vim works fine.

The problem stems from the variable `g:loaded_man`, which is also used in neovim runtime files:
```
k2:/usr/share/nvim/runtime % grep -r g:loaded_man
plugin/man.vim:let g:loaded_man = 
k2:/usr/share/nvim/runtime % yaourt -Qo plugin/man.vim 
/usr/share/nvim/runtime/plugin/man.vim is owned by neovim 0.1.0-1
```

Could vim-man use a more distinctive name for the guard variable?

**Comment by bruno-** [comment]
Thanks for reporting and opening a PR, it has been merged.
