### ISSUE TITLE
[neovim] completion doesn't work

### ISSUE THREAD

**Issue by alx741** [vim-utils/vim-man#36]
In Neovim hitting <tab> puts a **^I** and doesn't complete.
Also the command `:Man` opens a vertical split rather than a horizontal one.

I've tried the same `.vimrc` with Vim and both things work perfectly.

**Comment by nhooyr** [comment]
Completion is now in the neovim man plugin! See neovim/neovim#4449

**Comment by alx741** [comment]
awesome!
